import Head from 'next/head'
import SimpleLayout from '../components/SimpleLayout'

const BUILD_TOS = () => (
    <SimpleLayout>
        <Head>
        <title>Blink Build Terms of Service</title>
        <meta
          name="keywords"
          content="blink, build, shell, terminal, mosh, ios, ssh, emulator, code editor"
        />
      </Head>
        <h1 id="blink-build-terms-of-service">Blink Build Terms of Service</h1>
        <h2 id="agreement-to-terms"><strong>Agreement to Terms</strong></h2>
        <p>This service is operated by Blink Shell, Inc. Throughout this document and the service, the terms “we”, “us” and “our” refer to Blink Shell Inc. Blink Shell Inc. offers this website, products, services, tools, content, features and applications available to you, the User (“User”, “you” and “your”), conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
        <p>By accessing or using our Service and/or purchasing something from us, you engage in our “Service” and agree to be bound by the following terms and conditions (“TOS”, “Terms of Service”, “Terms”), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms apply to all visitors, users, and others who wish to access or use the Service_._ Any new features or tools which are added to the current Service shall also be subject to the Terms of Service. If you disagree with any part of these Terms then you do not have permission to access the Service.</p>
        <p>You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.</p>
        <h2 id="eligibility--registration"><strong>Eligibility &amp; Registration</strong></h2>
        <ul>
            <li>You may not use our Services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws, rules or regulations in your jurisdiction (including but not limited to copyright laws).</li>
            <li>The Service is targeted for users who are at least 18 years old. By using the Services, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this Service.</li>
            <li>To access the Services you may be required to register with the Websites for an account (“Account”). Your submission of personal information through the Service is governed by our <a href="blink.sh/pp">Privacy Policy</a>.</li>
            <li>You are responsible for maintaining the confidentiality of your Account and password and for restricting access to your devices, and you agree to accept responsibility for all activities that occur under your Account/password. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
        </ul>
        <h2 id="property-rights"><strong>Property Rights</strong></h2>
        <ul>
            <li>As between you and Blink Shell Inc, the Services are owned and/or provided by Blink Shell Inc. The names, logos, trademarks, visual interfaces, graphics, computer code (including source code or object code), software, services, and all other elements of the Websites and Services (“Materials”) that we provide are protected by intellectual property and other laws. All Materials included in the Services are the property of Blink Shell Inc or its third party licensors. You may only use the Services as expressly authorized by us and as set forth in this TOS. You shall abide by and maintain all intellectual property notices, information, and restrictions contained in the Services. We reserve all rights to the Services not granted expressly in this TOS.</li>
            <li>If you send creative ideas, source code, contributions, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, &#39;Contributions&#39;), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any manner and purpose any comments that you forward to us. We are and shall be under no obligation (1) to maintain any Contributions in confidence; (2) to pay compensation for any Contributions; or (3) to respond to any Contributions.</li>
            <li>Blink Shell Inc provides some Materials that are covered by one or more open source, Creative Commons, or equivalent licenses (known collectively as &quot;Open Source Licenses&quot;). This TOS don’t stop or restrict you from acquiring these materials under the relevant Open Source Licenses, nor does it aim to restrict your usage of them under those licenses.</li>
            <li>Subject your eligibility and compliance to these TOS, you are granted a non-exclusive, non-transferable, revocable license to access and use the Service for your personal and non-commercial use.</li>
        </ul>
        <h2 id="services-content"><strong>Services Content</strong></h2>
        <ul>
            <li>When using our Services you will provide us with files, software, processes, data, media, settings and other information for storage, hosting or processing by the Services (your “Services Content”).</li>
            <li>To provide our Services, you give us permission to host, store and transfer your Services Content. This permission extends to the Third Parties we may depend on to offer our Service. You retain any and all ownership rights that you may hold in your Services Content.</li>
            <li>You must set up and use the services properly, and take your own steps to keep your content safe, secure, encrypted, and backed up. Blink Shell does not guarantee to save any copies of your content. You are fully responsible for making sure your content stays intact, safe and backed up, even if the Service has backup or security features. Blink Shell Inc, will not be held responsible for any loss or unavailability of data, or any other consequences that may result from this, to the greatest extent allowed by law.</li>
            <li>When purchasing the Services, you may specify the geographic region and jurisdiction in which your Services Content will be stored. You consent to the storage of your Services Content in, and transfer of your Services Content into, the geographic region and jurisdiction you select. In order to provide the Services, you agree that Blink Shell may transfer and store your Services Content in other geographic regions or jurisdictions at its sole discretion. You represent and warrant that such storage and transfer are adequately consented to by you and permissible pursuant to applicable laws, regulations, rules, and third party rights.</li>
            <li>You acknowledge that the Services provided through remote servers and applications are not intended for full-time usage and that Blink Shell Inc has the right to delete or shut down relevant servers at any time to ensure the security and stability of our Service, or for any other reason.</li>
        </ul>
        <h2 id="rules-of-conduct"><strong>Rules of Conduct</strong></h2>
        <ul>
            <li>Our Services may allow third-parties (“Collaborators”) to access your Services Content. You are not allowed to use the Services for public-facing websites, applications, interfaces, and other public manifestations of your Services Content. You are not allowed to use the Services for commercial purposes or personal benefit, without advanced written permission from us.</li>
            <li>You are solely responsible for your Service Content, Collaborators and any activity by your Collaborators and their compliance to this TOS. Blink Shell Inc will not be liable for your Services Content, Collaborators and/or activity by your Collaborators.</li>
            <li>You shall not (directly or indirectly): (i) bypass, disable, or interfere with any security features of the Service, or features that prevent the copying of any Material or limit the use of the Service or Materials; (ii) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any tools, software, source code or underlying ideas or algorithms of any part of the Services (including without limitation any application), except to the limited extent applicable laws specifically prohibit such restriction; (iii) modify, translate, or otherwise create derivative works of any part of the Services; or (iv) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder.</li>
            <li>We reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) respond to any applicable law, regulation, legal process or governmental request; (ii) enforce this TOS, including investigation of potential violations hereof; (iii) detect, prevent, or otherwise address fraud, security or technical issues; (iv) respond to user support requests; or (v) protect the rights, property or safety of us, our users and the public.</li>
            <li>You shall abide by all applicable local, state, national and international laws and regulations. To the extent any portions of the Websites or Services are subject to Open Source Licenses, such Open Source Licenses apply regardless of this section.</li>
        </ul>
        <h2 id="prohibited-uses">Prohibited Uses</h2>
        <p>The use cases outlined here will constitute a violation of our usage policy and in consequence a violation of the TOS. We reserve the right to terminate the Service, even if a violation occurs unintentionally by you or your Collaborators and without your permission, without the need to provide prior notification to the User, and at any time within our sole discretion. This list may not be exhaustive and we reserve the right to take action even if a violation is not specifically described below.</p>
        <ul>
            <li>Use the Services to promote, engage or conduct illegal activities, like the distribution of content that has been determined by a court of competent jurisdiction to be unlawful.</li>
            <li>Use the Services to sell or distribute controlled substances.</li>
            <li>Use the Services to deceive or harm others, or to harm our reputation or our third parties, including pyramid schemes and the like.</li>
            <li>Use the Services to mine any cryptocurrency.</li>
            <li>Use the Service for content that incites violence, harassing or abuse, illegal conduct or activities.</li>
            <li>Unlawful Pornography, disseminating child pornography or depictions of nudity or sexual activity obtained or disseminated without the consent of those depicted (e.g., “revenge pornography”).</li>
            <li>Use the Services to violate Intellectual Property rights.</li>
            <li>Use Services to violate the security or integrity of any network, computer or communications system, software application, or network or computing device (each, a “System”, including the Service itself).</li>
            <li>Use the Services to distribute technology that may damage computer systems, like viruses, worms or Trojan horses.</li>
            <li>Accessing or using any System without permission, including testing vulnerabilities, breaching security, load testing, and others, without prior consent.</li>
            <li>Vulnerability testing of our Service or that of our Third-Parties, without prior consent.</li>
            <li>Interfere with or disrupt any System, including to attack or tamper with the Service, other websites, services and individuals (retaliation).</li>
            <li>Use the Service network to establish connections with other hosts or networks without permission to communicate with them.</li>
            <li>Launch any automated system, monitoring traffic or crawling of a System, include “robots”, or “spiders”, in a way that impairs or disrupts the System being monitored or crawled.</li>
            <li>Falsification of Origin, like impersonating another person through email or other means.</li>
            <li>Use the Services to hide or obscure Identity or Contact Information, such as return mailing and IP addresses.</li>
            <li>Create accounts with automation or register accounts in bulk without prior consent.</li>
            <li>Use the Services to operate certain network services that may circumvent access control measure, like open Proxies, Mail relays, recursive domain name servers, Tor exit nodes, or other similar network services.</li>
            <li>E-Mail and any other unsolicited messaging abuse, including junk mail or spam.</li>
            <li>Excessive use of Shared System Resources in a way that interferes or creates a burden on the Service or the networks or third-party services.</li>
        </ul>
        <h2 id="purchases"><strong>Purchases</strong></h2>
        <p>With regards to purchases made through app stores such as Apple&#39;s App Store, you are bound to comply with their Terms of Service.</p>
        <p>The Service offers virtual Credits that can be used for certain Account features, but these Credits have no real-world value and cannot be exchanged for real money or anything else of value. Credits are tied to your Account and cannot be transferred to others, nor can they be redeemed or refunded. We reserve the right to change the value or price of Credits at any time, subject to applicable law. Credits may expire based on the terms of this Agreement, upon termination of the Service, or upon termination of this Agreement. Credits do not grant you any personal property rights.</p>
        <p>The Service will not send you a statement of itemized transactions for your Credits balance. To check your Credits balance or view your recent transactions, visit the Account section within the application. You are responsible for verifying that the correct amount of Credits has been added to or deducted from your balance.</p>
        <p>Blink Shell Inc has the sole discretion to deactivate, suspend, reduce, terminate, or liquidate your Credits balance or other Service features in case Blink Shell Inc determines that you have violated this Agreement.</p>
        <h2 id="errors-inaccuracies-and-omissions"><strong>Errors, Inaccuracies and Omissions</strong></h2>
        <p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, offerings and product features. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information if any information in the Service or on any related website is inaccurate at any time without prior notice.</p>
        <p>We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.</p>
        <h2 id="beta-services"><strong>Beta Services</strong></h2>
        <p>We may offer “beta” versions or features of the Services (each, a <strong>“Beta Service”</strong>). Any production candidate or non-production version of Services or other version of the Services designated as a beta or testing version is considered a Beta Service under this TOS. We will determine, at our sole discretion, the availability, duration, features, and components of each Beta Service. If we permit you to use a Beta Service, you agree that information we provide relating to the Beta Service is Confidential Information where specified, and you specifically agree, in addition to the other requirements set forth in this TOS, to not: (i) use the Beta Service for benchmarking or performance testing or to publicly disseminate performance information or analysis from any source relating to the Service; (ii) modify or create derivative works of the Beta Service or remove any product identification, proprietary, copyright or other notices contained in the Beta Service; or (iii) allow any other individual to access or use the Beta Service. We, at our sole discretion, shall determine whether or not to continue to offer any Beta Service, and may cease offering any Beta Service at any time.</p>
        <h2 id="disclaimer-of-warranties-limitation-of-liability"><strong>Disclaimer of Warranties; Limitation of Liability</strong></h2>
        <p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.</p>
        <p>We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</p>
        <p>You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.</p>
        <p>You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and Services delivered to you through the service are (except as expressly stated by us) provided &#39;as is&#39; and &#39;as available&#39; for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
        <p>In no case shall Blink Shell Inc., our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the Service or any products procured using the Service, or for any other claim related in any way to your use of the Service or any product, including, but not limited to, any unauthorized access to or use of our Service, any interruption or cessation of transmission to or from the Service, any bugs, viruses, Trojan horses or the like which may be transmitted to or through our Service by any third party, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the Service, even if advised of their possibility.</p>
        <p>OTHER THAN FOR THE TYPES OF LIABILITY WE CANNOT LIMIT BY LAW (AS DESCRIBED IN THIS SECTION), WE LIMIT OUR LIABILITY TO YOU TO THE GREATER OF $20 USD OR 100% OF ANY AMOUNT YOU&#39;VE PAID UNDER YOUR CURRENT SERVICE PLAN WITH BLINK SHELL.</p>
        <p>Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
        <h2 id="indemnification"><strong>Indemnification</strong></h2>
        <p>You agree to indemnify, defend and hold harmless Blink Shell Inc. and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
        <h2 id="severability"><strong>Severability</strong></h2>
        <p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
        <h2 id="termination"><strong>Termination</strong></h2>
        <p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.</p>
        <p>These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.</p>
        <p>If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
        <h2 id="entire-agreement"><strong>Entire Agreement</strong></h2>
        <p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.</p>
        <p>These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).</p>
        <p>Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
        <h2 id="governing-law"><strong>Governing Law</strong></h2>
        <p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of New York, United States, without regard to its conflict of law provisions.</p>
        <h2 id="changes-to-terms-of-service"><strong>Changes to Terms of Service</strong></h2>
        <p>You can review the most current version of the Terms of Service at any time at this page.</p>
        <p>We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
        <h2 id="contact">Contact</h2>
        <p>Questions about the Terms of Service should be sent to us at <a href="mailto:hello@blink.sh">hello@blink.sh</a></p>

    </SimpleLayout>
  )


export default BUILD_TOS